version: '3.2'
services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data/
    restart: always
    networks:
      - task_net

  task_node:
    image: public.ecr.aws/koii-network/task_node:latest
    command: yarn initialize-start
    depends_on: 
      - redis
    ports:
      - '8080:8080'
    env_file: .env-local

    container_name: task_node
    restart: always
    links:
      - redis:redis
    networks:
      - task_net
    volumes:
      - ./config/koii:/app/config
      - ./data:/app/data
      - ./namespace:/app/namespace
      - ./dist:/app/executables
   
networks:
  task_net:
    name: task_net
    driver: bridge

volumes:
  redis_data: